photo/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top#main'
  get 'top/login'
  post 'top/login'
  get 'top/logout'
  
  resources :pictures do
    
    member do 
      get "get_pic"
    end
    resources :comments, only: [:index, :new, :create, :destroy]
    resources :images, only: [:create, :destroy] do
     member do 
      get "get_img"
     end
    end
    
  end
  resources :likes, only: [:create, :destroy]
  resources :users, only: [:index, :new, :create, :show, :destroy]
end

photo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

photo/app/models/comment.rb
class Comment < ApplicationRecord
    validates :message, presence: true, length: {maximum: 140}
    validates :user_id, presence: true
    belongs_to :picture
    belongs_to :user
end

photo/app/models/image.rb
class Image < ApplicationRecord
    validates :body, presence: true, length: {maximum: 140}
    validates :img, presence: true
    validates :user_id, presence: true
    belongs_to :user
    belongs_to :picture
    has_many :likes, dependent: :destroy
    has_many :like_users, source: :user, through: :likes
    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end
  def like(user)
    likes.create(user_id: user.id)
  end
  
  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
  
  def liked?(user)
    like_users.include?(user)
  end
    
end

photo/app/models/picture.rb
class Picture < ApplicationRecord
    validates :info, presence: true, length: {maximum: 140}
    validates :file, presence: true
    validates :title, presence: true
    validates :user_id, presence: true
    belongs_to :user
    has_many :images, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :comment_users, through: :comments, source: :user
    has_many :image_users, through: :images, source: :user
    has_many :likes, dependent: :destroy
    has_many :like_users, source: :user, through: :likes
    def liked_by?(user)
        likes.where(user_id: user.id).exists?
    end
    def like(user)
    likes.create(user_id: user.id)
    end
  
    def unlike(user)
      likes.find_by(user_id: user.id).destroy
    end
  
    def liked?(user)
      like_user.include?(user)
    end
end

photo/app/models/user.rb
class User < ApplicationRecord
    validates :password_i, presence: true, confirmation: true
    validates :name, presence: true, uniqueness: true
    
    has_many :pictures, dependent: :destroy
    has_many :images, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :comment_pictures, through: :comments, source: :picture
    has_many :image_pictures, through: :images, source: :picture
    attr_accessor :password_i, :password_i_confirmation
    has_many :likes, dependent: :destroy
    has_many :like_pictures, source: :picture, through: :likes
    has_many :like_images, source: :image, through: :likes
   
    def password_i=(val)
     if val.present?
       self.password = BCrypt::Password.create(val)
     end
     @password_i = val
#     byebug
    end
  
    def self.authenticate(name, pass)
    user = User.find_by(name: name)
    if user and BCrypt::Password.new(user.password) == pass
      user
    else
      nil
    end

    end
end

photo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        if session[:login_uid]
            User.find_by(name: session[:login_uid])
        end
    end
    helper_method :current_user
    
end

photo/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    
    def create 
       @picture = Picture.find(params[:picture_id])
       @comment = @picture.comments.build(message: params[:comment][:message])
       @comment.user_id = current_user.id
     if @comment.save
      redirect_to picture_path(@picture)
     else
      redirect_to root_path
     end
    end
    
    def destroy
     @picture = Picture.find(params[:picture_id])
     @comment = @picture.comments.find(params[:id])
     @comment.destroy 
     redirect_to picture_path(@picture)
    end
end

photo/app/controllers/images_controller.rb
class ImagesController < ApplicationController
    def create
     user_id = User.find_by(name: session[:login_uid]).id
     @picture = Picture.find(params[:picture_id])
     img = params[:image][:img].read
     @image = @picture.images.new(img: img, body: params[:image][:body], user_id: user_id)
     if @image.save
      redirect_to picture_path(@picture)
      flash[:post] = "投稿しました"
     else
      render new_image_path
      flash[:failed] = "投稿に失敗しました"
     end
    end
    
    def destroy
     @picture = Picture.find(params[:picture_id])
     @image = @picture.images.find(params[:id])
     @image.destroy
     redirect_to picture_path(@picture)
     flash[:delete] = "投稿を削除しました"
    end
   
    def get_img
       
       image = @picture.images.find(params[:id])
       send_data image.img, disposition: :inline, type:'image/png'
    end
end

photo/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    def index
        @pictures = Picture.all
    end
    
    def new
       @picture = Picture.new 
    end
    
    def create
     user_id = User.find_by(name: session[:login_uid]).id
     file = params[:picture][:file].read
     @picture = Picture.new(title: params[:picture][:title], file: file, info: params[:picture][:info], user_id: user_id)
     if @picture.save
      redirect_to root_path
      flash[:post] = "投稿しました"
     else
      render new_picture_path
      flash[:failed] = "投稿に失敗しました"
     end
    end
    def show
        @picture = Picture.find(params[:id])
        @comments = @picture.comments
        @comment = Comment.new
        @images = @picture.images
        @image = Image.all
    end
    
    def destroy
     picture = Picture.find(params[:id])
     picture.destroy
     redirect_to root_path
     flash[:delete] = "投稿を削除しました"
    end
    
    def edit
        @picture = Picture.find(params[:id])
    end
    
    def update
        @picture = Picture.find(params[:id])
        file = params[:picture][:file].read
        @picture.update(title: params[:picture][:title], file: file, info: params[:picture][:info])
        if @picture.save
            flash[:update] = "更新しました！"
            redirect_to root_path
        else
            flash[:fail] = "更新に失敗しました。"
            render :edit
        end
    end
    def get_pic
       picture = Picture.find(params[:id])
       send_data picture.file, disposition: :inline, type:'image/png'
    end

end

photo/app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        @pictures = Picture.all
    end
    
    def login
        user = User.authenticate(params[:name], params[:password])
         if user
          session[:login_uid] = params[:name]
          redirect_to root_path
          flash[:success] = "ログインしました"
         else
          render top_login_path
          flash[:error] = "ユーザー名またはパスワードが違います"
          
         end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
        flash[:out] = "ログアウトしました"
    end
end

photo/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @user = User.all
        @pictures = current_user.pictures.all
    end
    
    def new
        @user = User.new
    end
    
    def create
      @user = User.new(name: params[:user][:name],
      password_i: params[:user][:password_i],
      password_i_confirmation: params[:user][:password_i_confirmation])
      if @user.save
         redirect_to top_login_path
      else
         render 'new'
      end
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def destroy
      user = User.find(params[:id])
      user.destroy
      redirect_to users_path
    end
  
end

photo/app/helpers/application_helper.rb
module ApplicationHelper
end

photo/app/helpers/comments_helper.rb
module CommentsHelper
end

photo/app/helpers/images_helper.rb
module ImagesHelper
end

photo/app/helpers/likes_helper.rb
module LikesHelper
end

photo/app/helpers/pictures_helper.rb
module PicturesHelper
end

photo/app/helpers/top_helper.rb
module TopHelper
end

photo/app/helpers/users_helper.rb
module UsersHelper
end

photo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

photo/app/views/pictures/edit.html.erb
<h2>編集ページ</h2>
<%= form_for @picture, url: {action: :update} do |p| %>

<p>
  <%= p.label :title, 'タイトル' %>
  <%= p.text_field :title %>
</p>
<p>
  <%= p.label :file, '写真' %>
  <%= p.file_field :file %>
</p>
<p>
  <%= p.label :info, '説明' %>
  <%= p.text_field :info %>
</p>
<p>
  <%= p.submit '更新' %>
</p>
<% end %>

<p><%= link_to '戻る', :back %>

photo/app/views/pictures/index.html.erb
<% if flash[:info] %>
<%= flash[:info] %>
<% end %>

<% if @picture.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @picture.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= link_to '新規追加', new_picture_path %>
<% @picture.each do |p| %>
<p>
  <%= p_tag "/get_pic/#{p.id}" %>
  <%= link_to '削除', picture_path(p), method: :delete, data: { confirm: '削除していいですか？' }  %>
</p>
<% end %>

<% @pictures.each do |p| %>
<p>
  <%= p_tag "/get_pic/#{p.id}" %>
</p>
<% end %>

<p><%= link_to 'ログアウト', top_logout_path %></p>

photo/app/views/pictures/new.html.erb
<h2>新規投稿</h2>
<%= form_for @picture, url: {action: :create} do |p| %>
<% if flash[:failed] %>
    <p><font color="red"><%= flash[:failed] %></font></p>
<% end %>

<p>
  <%= p.label :title, 'タイトル' %>
  <%= p.text_field :title %>
</p>
<p>
  <%= p.label :file, '写真' %>
  <%= p.file_field :file %>
</p>
<p>
  <%= p.label :info, '説明' %>
  <%= p.text_field :info %>
</p>
<p>
  <%= p.submit '投稿' %>
</p>
<% end %>

<p><%= link_to '戻る', :back %>

photo/app/views/pictures/show.html.erb
<h2>詳細ページ</h2>
<p class="simple_square_btn"><%= link_to 'ログアウト', top_logout_path %></p>
<p class="my_btn"><%= link_to 'マイページ', user_path(current_user) %></p>
<p class="top_btn"><%= link_to 'TOP', root_path %></p>
<h3 class="pic">投稿者：<%= link_to @picture.user.name, user_path(@picture.user.id) %></h3>

<pre class="stitch" >
<p>
    <%= @picture.title %>
</p>

    <%= image_tag get_pic_picture_path(@picture), :width => '500', :height => '520' %>

<h4>
    <%= @picture.info %>
</h4>    
</pre>



<h3 class="pic">イラスト</h3>
<% @picture.images.each do |i| %>
<div class="inline-block">
  <p>
     <%= link_to User.find(i.user_id).name, user_path(i.user.id) %><br><%= image_tag get_img_picture_image_path(i), :width => '300', :height => '320' %><br><%= i.body %>
     <% if current_user and i.user.id == current_user.id %>
     <%= link_to 'delete', [i.picture, i], :confirm => 'よろしいですか？', :method => :delete %>
     <% end %>
  </p>   
</div>  
<% end %>

<%= form_for([@picture, @picture.images.build]) do |f| %>
  <%= f.file_field :img %>
  <%= f.text_area :body %>
  <%= f.submit 'イラスト投稿' %>
<% end %> 

<h3 class="pic">コメント</h3>
<% @picture.comments.each do |c| %>
  <p>
     <font color="black"><span class='c_name'><%= link_to User.find(c.user_id).name, user_path(c.user.id) %></span><span class="comment"><%= c.message %></span> 
     <% if current_user and c.user.id == current_user.id %>
     <%= link_to 'delete', [c.picture, c], :confirm => 'よろしいですか？', :method => :delete %>
     <% end %>
     </font>
  </p>      
<% end %>

<%= form_for([@picture, @picture.comments.build]) do |f| %>
  <%= f.text_area :message %>
  <%= f.submit 'コメントする' %>
<% end %>  








<%= link_to '戻る', :back %>

photo/app/views/top/login.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/top.scss" >
</head>
<h2>ログイン画面</h2>
<% if flash[:error] %>
    <p><font color="red"><%= flash[:error] %></font></p>
<% end %>


<%= form_tag top_login_path, method: :post  do  %>
    <%= label_tag :name, 'ユーザ名' %>
    <%= text_field_tag :name %>
    <%= label_tag :password, 'パスワード' %>
    <%= password_field_tag :password %>
    <%= submit_tag 'ログイン' %>
<% end %>

<p><%= link_to '戻る', :back %>
<br>
<p><%= link_to "ユーザ登録", new_user_path %></p>

photo/app/views/top/main.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/top.scss">
</head>
<body>
<h2><span class="under">TOP</span></h2>

<% if current_user %>
  <p class="simple_square_btn"><%= link_to 'ログアウト', top_logout_path %></p>
  <p class="my_btn"><%= link_to 'マイページ', user_path(current_user) %></p>
  <p class="new_btn"><%= link_to '新規投稿', new_picture_path %></p>
<% else %>
  <p class="simple_square_btn"><%= link_to 'ログイン', top_login_path %></p>
<% end %>
<% if flash[:success] %>
    <p><font color="green"><%= flash[:success] %></font></p>
<% end %>
<% if flash[:out] %>
    <p><font color="blue"><%= flash[:out] %></font></p>
<% end %>
<% if flash[:post] %>
    <p><font color="green"><%= flash[:post] %></font></p>
<% end %>
<% if flash[:update] %>
    <p><font color="blue"><%= flash[:update] %></font></p>
<% end %>
<% if flash[:delete] %>
    <p><font color="red"><%= flash[:delete] %></font></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>user</th>
      <th>Title</th>
      <th>Picture</th>
      <th>Request</th>
      <% if current_user %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead>
    <tbody>
    <% @pictures.each do |p| %>
      <tr>
        <td><%= link_to p.user.name, user_path(p.user.id) %></td>
        <td><%= p.title %></td>
        <td><%= image_tag get_pic_picture_path(p), :width => '200', :height => '220' %></td>
        <td><%= p.info %></td>
        <% if current_user %>
        <td>
         <%= link_to 'Show', p %>
        <% end %> 
        <% if current_user and p.user.id == current_user.id %>
         <%= link_to 'Edit', edit_picture_path(p) %>
         <%= link_to 'Destroy', picture_path(p), method: :delete %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
</table>

</body>

photo/app/views/users/new.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/users.scss">
</head>
<h2>ユーザ登録</h2>
<% if @user.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user, url: {action: :create} do |u| %>
<p>
  <%= u.label :name, 'ユーザ名' %>
  <%= u.text_field :name %>
</p>
<p>
  <%= u.label :password_i, 'パスワード' %>
  <%= u.password_field :password_i %>
</p>
<p>
  <%= u.label :password_i_confirmation, 'パスワード（確認）' %>
  <%= u.password_field :password_i_confirmation %>
</p>
<p>
  <%= u.submit '登録' %>
</p>
<% end %>

<%= link_to '戻る', root_path %>

photo/app/views/users/show.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/users.scss">
</head>
<h2><%= @user.name %>'s Page</h2>
<p class="simple_square_btn"><%= link_to 'ログアウト', top_logout_path %></p>
<p class="my_btn"><%= link_to 'マイページ', user_path(current_user) %></p>
<p class="top_btn"><%= link_to 'TOP', root_path %></p>
<h3 class="pic">投稿した画像</h3>
<table>
  
<tbody>
<% @user.pictures.each do |post| %>
<tr>
 <td><%= post.title %></td>
 <td><%= image_tag get_pic_picture_path(post), :width => '270', :height => '320' %></td>
 <td><%= post.info %></td>
 <td><%= link_to 'Show', picture_path(post) %></td>
</tr>
<% end %> 
</tbody>
</table>

<h3 class="pic">描いたイラスト</h3>
<% @user.images.each do |post| %>
 <%= image_tag get_img_picture_image_path(post), :width => '270', :height => '320' %>
<% end %> 

<p><%= link_to "戻る", :back %></p>